//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.20.0.3
//     Timestamp      : 2024/8/17 7:46:41
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace FabDBFEd
    Public Partial Class BrowseWindow2 ;
        Inherit System.Windows.Forms.Form
        Private toolStripBar As System.Windows.Forms.ToolStrip
        Private statusStripBar As System.Windows.Forms.StatusStrip
        Private panel1 As System.Windows.Forms.Panel
        Private statusLabel As System.Windows.Forms.ToolStripStatusLabel
        Private leftButton As System.Windows.Forms.ToolStripButton
        Private rightButton As System.Windows.Forms.ToolStripButton
        Private bottomButton As System.Windows.Forms.ToolStripButton
        Private toolStripSeparator1 As System.Windows.Forms.ToolStripSeparator
        Private appendButton As System.Windows.Forms.ToolStripButton
        Private deleteButton As System.Windows.Forms.ToolStripButton
        Private topButton As System.Windows.Forms.ToolStripButton
        Private dbfBrowseView As System.Windows.Forms.DataGridView
        Private components := Null As System.ComponentModel.IContainer
                                                                                                                                                                                                                                                                                                                                                                                                                
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Method Dispose(disposing As Logic) As Void Strict

            If (disposing .AND. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
            Return

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
                Private Method InitializeComponent() As Void Strict
            Local resources := System.ComponentModel.ComponentResourceManager{Typeof(BrowseWindow2)} As System.ComponentModel.ComponentResourceManager
            Local dataGridViewCellStyle1 := System.Windows.Forms.DataGridViewCellStyle{} As System.Windows.Forms.DataGridViewCellStyle
            Self:toolStripBar := System.Windows.Forms.ToolStrip{}
            Self:topButton := System.Windows.Forms.ToolStripButton{}
            Self:leftButton := System.Windows.Forms.ToolStripButton{}
            Self:rightButton := System.Windows.Forms.ToolStripButton{}
            Self:bottomButton := System.Windows.Forms.ToolStripButton{}
            Self:toolStripSeparator1 := System.Windows.Forms.ToolStripSeparator{}
            Self:appendButton := System.Windows.Forms.ToolStripButton{}
            Self:deleteButton := System.Windows.Forms.ToolStripButton{}
            Self:statusStripBar := System.Windows.Forms.StatusStrip{}
            Self:statusLabel := System.Windows.Forms.ToolStripStatusLabel{}
            Self:panel1 := System.Windows.Forms.Panel{}
            Self:dbfBrowseView := System.Windows.Forms.DataGridView{}
            Self:toolStripBar:SuspendLayout()
            Self:statusStripBar:SuspendLayout()
            Self:panel1:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(Self:dbfBrowseView)):BeginInit()
            Self:SuspendLayout()
            // 
            // toolStripBar
            // 
            Self:toolStripBar:ImageScalingSize := System.Drawing.Size{20, 20}
            Self:toolStripBar:Items:AddRange(<System.Windows.Forms.ToolStripItem>{ Self:topButton, Self:leftButton, Self:rightButton, Self:bottomButton, Self:toolStripSeparator1, Self:appendButton, Self:deleteButton })
            resources:ApplyResources(Self:toolStripBar, "toolStripBar")
            Self:toolStripBar:Name := "toolStripBar"
            // 
            // topButton
            // 
            Self:topButton:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            resources:ApplyResources(Self:topButton, "topButton")
            Self:topButton:Name := "topButton"
            Self:topButton:Click += System.EventHandler{ Self, @topButton_Click() }
            // 
            // leftButton
            // 
            Self:leftButton:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            resources:ApplyResources(Self:leftButton, "leftButton")
            Self:leftButton:Name := "leftButton"
            Self:leftButton:Click += System.EventHandler{ Self, @leftButton_Click() }
            // 
            // rightButton
            // 
            Self:rightButton:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            resources:ApplyResources(Self:rightButton, "rightButton")
            Self:rightButton:Name := "rightButton"
            Self:rightButton:Click += System.EventHandler{ Self, @rightButton_Click() }
            // 
            // bottomButton
            // 
            Self:bottomButton:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            resources:ApplyResources(Self:bottomButton, "bottomButton")
            Self:bottomButton:Name := "bottomButton"
            Self:bottomButton:Click += System.EventHandler{ Self, @bottomButton_Click() }
            // 
            // toolStripSeparator1
            // 
            Self:toolStripSeparator1:Name := "toolStripSeparator1"
            resources:ApplyResources(Self:toolStripSeparator1, "toolStripSeparator1")
            // 
            // appendButton
            // 
            Self:appendButton:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            resources:ApplyResources(Self:appendButton, "appendButton")
            Self:appendButton:Name := "appendButton"
            Self:appendButton:Click += System.EventHandler{ Self, @appendButton_Click() }
            // 
            // deleteButton
            // 
            Self:deleteButton:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            resources:ApplyResources(Self:deleteButton, "deleteButton")
            Self:deleteButton:Name := "deleteButton"
            Self:deleteButton:Click += System.EventHandler{ Self, @deleteButton_Click() }
            // 
            // statusStripBar
            // 
            Self:statusStripBar:ImageScalingSize := System.Drawing.Size{20, 20}
            Self:statusStripBar:Items:AddRange(<System.Windows.Forms.ToolStripItem>{ Self:statusLabel })
            resources:ApplyResources(Self:statusStripBar, "statusStripBar")
            Self:statusStripBar:Name := "statusStripBar"
            // 
            // statusLabel
            // 
            Self:statusLabel:Name := "statusLabel"
            resources:ApplyResources(Self:statusLabel, "statusLabel")
            // 
            // panel1
            // 
            Self:panel1:Controls:Add(Self:dbfBrowseView)
            resources:ApplyResources(Self:panel1, "panel1")
            Self:panel1:Name := "panel1"
            // 
            // dbfBrowseView
            // 
            Self:dbfBrowseView:AllowUserToAddRows := false
            Self:dbfBrowseView:AllowUserToDeleteRows := false
            Self:dbfBrowseView:ColumnHeadersHeightSizeMode := System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            resources:ApplyResources(Self:dbfBrowseView, "dbfBrowseView")
            Self:dbfBrowseView:Name := "dbfBrowseView"
            dataGridViewCellStyle1:Alignment := System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
            dataGridViewCellStyle1:BackColor := System.Drawing.SystemColors.Control
            dataGridViewCellStyle1:Font := System.Drawing.Font{"Microsoft Sans Serif", 7.8, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((Byte)(0))}
            dataGridViewCellStyle1:ForeColor := System.Drawing.SystemColors.WindowText
            dataGridViewCellStyle1:SelectionBackColor := System.Drawing.SystemColors.Highlight
            dataGridViewCellStyle1:SelectionForeColor := System.Drawing.SystemColors.HighlightText
            dataGridViewCellStyle1:WrapMode := System.Windows.Forms.DataGridViewTriState.False
            Self:dbfBrowseView:RowHeadersDefaultCellStyle := dataGridViewCellStyle1
            Self:dbfBrowseView:RowTemplate:Height := 24
            Self:dbfBrowseView:CellFormatting += System.Windows.Forms.DataGridViewCellFormattingEventHandler{ Self, @dbfBrowseView_CellFormatting() }
            Self:dbfBrowseView:EditingControlShowing += System.Windows.Forms.DataGridViewEditingControlShowingEventHandler{ Self, @dbfBrowseView_EditingControlShowing() }
            Self:dbfBrowseView:RowEnter += System.Windows.Forms.DataGridViewCellEventHandler{ Self, @dbfBrowseView_RowEnter() }
            // 
            // BrowseWindow2
            // 
            resources:ApplyResources(Self, "$this")
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:Controls:Add(Self:panel1)
            Self:Controls:Add(Self:statusStripBar)
            Self:Controls:Add(Self:toolStripBar)
            Self:Name := "BrowseWindow2"
            Self:FormClosing += System.Windows.Forms.FormClosingEventHandler{ Self, @BrowseWindow_FormClosing() }
            Self:toolStripBar:ResumeLayout(false)
            Self:toolStripBar:PerformLayout()
            Self:statusStripBar:ResumeLayout(false)
            Self:statusStripBar:PerformLayout()
            Self:panel1:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(Self:dbfBrowseView)):EndInit()
            Self:ResumeLayout(false)
            Self:PerformLayout()
        End Method
                                                                                
        #endregion
    
    End Class 
End Namespace
