//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.6.0.0
//     Timestamp      : 11/02/2021 16:52:40
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE FabDBFEd
    PUBLIC PARTIAL CLASS BrowseWindow3 ;
        INHERIT System.Windows.Forms.Form
        PRIVATE statusStripBar AS System.Windows.Forms.StatusStrip
        PRIVATE statusLabel AS System.Windows.Forms.ToolStripStatusLabel
        PRIVATE dbfBrowseView AS System.Windows.Forms.DataGridView
        PRIVATE bindingNavigator1 AS System.Windows.Forms.BindingNavigator
        PRIVATE bindingNavigatorAddNewItem AS System.Windows.Forms.ToolStripButton
        PRIVATE bindingNavigatorCountItem AS System.Windows.Forms.ToolStripLabel
        PRIVATE bindingNavigatorDeleteItem AS System.Windows.Forms.ToolStripButton
        PRIVATE bindingNavigatorMoveFirstItem AS System.Windows.Forms.ToolStripButton
        PRIVATE bindingNavigatorMovePreviousItem AS System.Windows.Forms.ToolStripButton
        PRIVATE bindingNavigatorSeparator AS System.Windows.Forms.ToolStripSeparator
        PRIVATE bindingNavigatorPositionItem AS System.Windows.Forms.ToolStripTextBox
        PRIVATE bindingNavigatorSeparator1 AS System.Windows.Forms.ToolStripSeparator
        PRIVATE bindingNavigatorMoveNextItem AS System.Windows.Forms.ToolStripButton
        PRIVATE bindingNavigatorMoveLastItem AS System.Windows.Forms.ToolStripButton
        PRIVATE bindingNavigatorSeparator2 AS System.Windows.Forms.ToolStripSeparator
        PRIVATE bindingSource1 AS System.Windows.Forms.BindingSource
        PRIVATE panelMiddle AS System.Windows.Forms.Panel
        PRIVATE components := NULL AS System.ComponentModel.IContainer
                                                                                                                                                                                                                                                                                                                                                                                                                
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        PRIVATE METHOD InitializeComponent() AS VOID STRICT
            SELF:components := System.ComponentModel.Container{}
            LOCAL dataGridViewCellStyle1 := System.Windows.Forms.DataGridViewCellStyle{} AS System.Windows.Forms.DataGridViewCellStyle
            LOCAL resources := System.ComponentModel.ComponentResourceManager{TYPEOF(BrowseWindow3)} AS System.ComponentModel.ComponentResourceManager
            SELF:statusStripBar := System.Windows.Forms.StatusStrip{}
            SELF:statusLabel := System.Windows.Forms.ToolStripStatusLabel{}
            SELF:panelMiddle := System.Windows.Forms.Panel{}
            SELF:dbfBrowseView := System.Windows.Forms.DataGridView{}
            SELF:bindingNavigator1 := System.Windows.Forms.BindingNavigator{SELF:components}
            SELF:bindingNavigatorAddNewItem := System.Windows.Forms.ToolStripButton{}
            SELF:bindingSource1 := System.Windows.Forms.BindingSource{SELF:components}
            SELF:bindingNavigatorCountItem := System.Windows.Forms.ToolStripLabel{}
            SELF:bindingNavigatorDeleteItem := System.Windows.Forms.ToolStripButton{}
            SELF:bindingNavigatorMoveFirstItem := System.Windows.Forms.ToolStripButton{}
            SELF:bindingNavigatorMovePreviousItem := System.Windows.Forms.ToolStripButton{}
            SELF:bindingNavigatorSeparator := System.Windows.Forms.ToolStripSeparator{}
            SELF:bindingNavigatorPositionItem := System.Windows.Forms.ToolStripTextBox{}
            SELF:bindingNavigatorSeparator1 := System.Windows.Forms.ToolStripSeparator{}
            SELF:bindingNavigatorMoveNextItem := System.Windows.Forms.ToolStripButton{}
            SELF:bindingNavigatorMoveLastItem := System.Windows.Forms.ToolStripButton{}
            SELF:bindingNavigatorSeparator2 := System.Windows.Forms.ToolStripSeparator{}
            SELF:statusStripBar:SuspendLayout()
            SELF:panelMiddle:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(SELF:dbfBrowseView)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:bindingNavigator1)):BeginInit()
            SELF:bindingNavigator1:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(SELF:bindingSource1)):BeginInit()
            SELF:SuspendLayout()
            // 
            // statusStripBar
            // 
            SELF:statusStripBar:ImageScalingSize := System.Drawing.Size{20, 20}
            SELF:statusStripBar:Items:AddRange(<System.Windows.Forms.ToolStripItem>{ SELF:statusLabel })
            SELF:statusStripBar:Location := System.Drawing.Point{0, 307}
            SELF:statusStripBar:Name := "statusStripBar"
            SELF:statusStripBar:Padding := System.Windows.Forms.Padding{1, 0, 13, 0}
            SELF:statusStripBar:Size := System.Drawing.Size{535, 25}
            SELF:statusStripBar:TabIndex := 1
            SELF:statusStripBar:Text := "statusStripBar"
            // 
            // statusLabel
            // 
            SELF:statusLabel:Name := "statusLabel"
            SELF:statusLabel:Size := System.Drawing.Size{83, 20}
            SELF:statusLabel:Text := "statusLabel"
            // 
            // panelMiddle
            // 
            SELF:panelMiddle:Anchor := ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)  ;
                        | System.Windows.Forms.AnchorStyles.Left)  ;
                        | System.Windows.Forms.AnchorStyles.Right)))
            SELF:panelMiddle:Controls:Add(SELF:dbfBrowseView)
            SELF:panelMiddle:Location := System.Drawing.Point{0, 29}
            SELF:panelMiddle:Margin := System.Windows.Forms.Padding{3, 2, 3, 2}
            SELF:panelMiddle:Name := "panelMiddle"
            SELF:panelMiddle:Size := System.Drawing.Size{535, 276}
            SELF:panelMiddle:TabIndex := 0
            SELF:panelMiddle:Paint += System.Windows.Forms.PaintEventHandler{ SELF, @panel1_Paint() }
            // 
            // dbfBrowseView
            // 
            SELF:dbfBrowseView:AllowUserToAddRows := false
            SELF:dbfBrowseView:AllowUserToDeleteRows := false
            SELF:dbfBrowseView:BorderStyle := System.Windows.Forms.BorderStyle.None
            SELF:dbfBrowseView:ColumnHeadersHeightSizeMode := System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            SELF:dbfBrowseView:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:dbfBrowseView:Location := System.Drawing.Point{0, 0}
            SELF:dbfBrowseView:Margin := System.Windows.Forms.Padding{3, 2, 3, 2}
            SELF:dbfBrowseView:Name := "dbfBrowseView"
            dataGridViewCellStyle1:Alignment := System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
            dataGridViewCellStyle1:BackColor := System.Drawing.SystemColors.Control
            dataGridViewCellStyle1:Font := System.Drawing.Font{"Microsoft Sans Serif", 7.8, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
            dataGridViewCellStyle1:ForeColor := System.Drawing.SystemColors.WindowText
            dataGridViewCellStyle1:SelectionBackColor := System.Drawing.SystemColors.Highlight
            dataGridViewCellStyle1:SelectionForeColor := System.Drawing.SystemColors.HighlightText
            dataGridViewCellStyle1:WrapMode := System.Windows.Forms.DataGridViewTriState.False
            SELF:dbfBrowseView:RowHeadersDefaultCellStyle := dataGridViewCellStyle1
            SELF:dbfBrowseView:RowTemplate:Height := 24
            SELF:dbfBrowseView:Size := System.Drawing.Size{535, 276}
            SELF:dbfBrowseView:TabIndex := 0
            SELF:dbfBrowseView:CellFormatting += System.Windows.Forms.DataGridViewCellFormattingEventHandler{ SELF, @dbfBrowseView_CellFormatting() }
            SELF:dbfBrowseView:EditingControlShowing += System.Windows.Forms.DataGridViewEditingControlShowingEventHandler{ SELF, @dbfBrowseView_EditingControlShowing() }
            SELF:dbfBrowseView:RowEnter += System.Windows.Forms.DataGridViewCellEventHandler{ SELF, @dbfBrowseView_RowEnter() }
            // 
            // bindingNavigator1
            // 
            SELF:bindingNavigator1:AddNewItem := SELF:bindingNavigatorAddNewItem
            SELF:bindingNavigator1:BindingSource := SELF:bindingSource1
            SELF:bindingNavigator1:CountItem := SELF:bindingNavigatorCountItem
            SELF:bindingNavigator1:DeleteItem := SELF:bindingNavigatorDeleteItem
            SELF:bindingNavigator1:ImageScalingSize := System.Drawing.Size{20, 20}
            SELF:bindingNavigator1:Items:AddRange(<System.Windows.Forms.ToolStripItem>{ SELF:bindingNavigatorMoveFirstItem, SELF:bindingNavigatorMovePreviousItem, SELF:bindingNavigatorSeparator, SELF:bindingNavigatorPositionItem, SELF:bindingNavigatorCountItem, SELF:bindingNavigatorSeparator1, SELF:bindingNavigatorMoveNextItem, SELF:bindingNavigatorMoveLastItem, SELF:bindingNavigatorSeparator2, SELF:bindingNavigatorAddNewItem, SELF:bindingNavigatorDeleteItem })
            SELF:bindingNavigator1:Location := System.Drawing.Point{0, 0}
            SELF:bindingNavigator1:MoveFirstItem := SELF:bindingNavigatorMoveFirstItem
            SELF:bindingNavigator1:MoveLastItem := SELF:bindingNavigatorMoveLastItem
            SELF:bindingNavigator1:MoveNextItem := SELF:bindingNavigatorMoveNextItem
            SELF:bindingNavigator1:MovePreviousItem := SELF:bindingNavigatorMovePreviousItem
            SELF:bindingNavigator1:Name := "bindingNavigator1"
            SELF:bindingNavigator1:PositionItem := SELF:bindingNavigatorPositionItem
            SELF:bindingNavigator1:Size := System.Drawing.Size{535, 27}
            SELF:bindingNavigator1:TabIndex := 0
            SELF:bindingNavigator1:Text := "bindingNavigator1"
            // 
            // bindingNavigatorAddNewItem
            // 
            SELF:bindingNavigatorAddNewItem:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            SELF:bindingNavigatorAddNewItem:Image := ((System.Drawing.Image)(resources:GetObject("bindingNavigatorAddNewItem.Image")))
            SELF:bindingNavigatorAddNewItem:Name := "bindingNavigatorAddNewItem"
            SELF:bindingNavigatorAddNewItem:RightToLeftAutoMirrorImage := true
            SELF:bindingNavigatorAddNewItem:Size := System.Drawing.Size{24, 24}
            SELF:bindingNavigatorAddNewItem:Text := "Add new"
            // 
            // bindingNavigatorCountItem
            // 
            SELF:bindingNavigatorCountItem:Name := "bindingNavigatorCountItem"
            SELF:bindingNavigatorCountItem:Size := System.Drawing.Size{45, 24}
            SELF:bindingNavigatorCountItem:Text := "of {0}"
            SELF:bindingNavigatorCountItem:ToolTipText := "Total number of items"
            // 
            // bindingNavigatorDeleteItem
            // 
            SELF:bindingNavigatorDeleteItem:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            SELF:bindingNavigatorDeleteItem:Image := ((System.Drawing.Image)(resources:GetObject("bindingNavigatorDeleteItem.Image")))
            SELF:bindingNavigatorDeleteItem:Name := "bindingNavigatorDeleteItem"
            SELF:bindingNavigatorDeleteItem:RightToLeftAutoMirrorImage := true
            SELF:bindingNavigatorDeleteItem:Size := System.Drawing.Size{24, 24}
            SELF:bindingNavigatorDeleteItem:Text := "Delete"
            // 
            // bindingNavigatorMoveFirstItem
            // 
            SELF:bindingNavigatorMoveFirstItem:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            SELF:bindingNavigatorMoveFirstItem:Image := ((System.Drawing.Image)(resources:GetObject("bindingNavigatorMoveFirstItem.Image")))
            SELF:bindingNavigatorMoveFirstItem:Name := "bindingNavigatorMoveFirstItem"
            SELF:bindingNavigatorMoveFirstItem:RightToLeftAutoMirrorImage := true
            SELF:bindingNavigatorMoveFirstItem:Size := System.Drawing.Size{24, 24}
            SELF:bindingNavigatorMoveFirstItem:Text := "Move first"
            // 
            // bindingNavigatorMovePreviousItem
            // 
            SELF:bindingNavigatorMovePreviousItem:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            SELF:bindingNavigatorMovePreviousItem:Image := ((System.Drawing.Image)(resources:GetObject("bindingNavigatorMovePreviousItem.Image")))
            SELF:bindingNavigatorMovePreviousItem:Name := "bindingNavigatorMovePreviousItem"
            SELF:bindingNavigatorMovePreviousItem:RightToLeftAutoMirrorImage := true
            SELF:bindingNavigatorMovePreviousItem:Size := System.Drawing.Size{24, 24}
            SELF:bindingNavigatorMovePreviousItem:Text := "Move previous"
            // 
            // bindingNavigatorSeparator
            // 
            SELF:bindingNavigatorSeparator:Name := "bindingNavigatorSeparator"
            SELF:bindingNavigatorSeparator:Size := System.Drawing.Size{6, 27}
            // 
            // bindingNavigatorPositionItem
            // 
            SELF:bindingNavigatorPositionItem:AccessibleName := "Position"
            SELF:bindingNavigatorPositionItem:AutoSize := false
            SELF:bindingNavigatorPositionItem:Name := "bindingNavigatorPositionItem"
            SELF:bindingNavigatorPositionItem:Size := System.Drawing.Size{50, 27}
            SELF:bindingNavigatorPositionItem:Text := "0"
            SELF:bindingNavigatorPositionItem:ToolTipText := "Current position"
            // 
            // bindingNavigatorSeparator1
            // 
            SELF:bindingNavigatorSeparator1:Name := "bindingNavigatorSeparator1"
            SELF:bindingNavigatorSeparator1:Size := System.Drawing.Size{6, 27}
            // 
            // bindingNavigatorMoveNextItem
            // 
            SELF:bindingNavigatorMoveNextItem:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            SELF:bindingNavigatorMoveNextItem:Image := ((System.Drawing.Image)(resources:GetObject("bindingNavigatorMoveNextItem.Image")))
            SELF:bindingNavigatorMoveNextItem:Name := "bindingNavigatorMoveNextItem"
            SELF:bindingNavigatorMoveNextItem:RightToLeftAutoMirrorImage := true
            SELF:bindingNavigatorMoveNextItem:Size := System.Drawing.Size{24, 24}
            SELF:bindingNavigatorMoveNextItem:Text := "Move next"
            // 
            // bindingNavigatorMoveLastItem
            // 
            SELF:bindingNavigatorMoveLastItem:DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image
            SELF:bindingNavigatorMoveLastItem:Image := ((System.Drawing.Image)(resources:GetObject("bindingNavigatorMoveLastItem.Image")))
            SELF:bindingNavigatorMoveLastItem:Name := "bindingNavigatorMoveLastItem"
            SELF:bindingNavigatorMoveLastItem:RightToLeftAutoMirrorImage := true
            SELF:bindingNavigatorMoveLastItem:Size := System.Drawing.Size{24, 24}
            SELF:bindingNavigatorMoveLastItem:Text := "Move last"
            // 
            // bindingNavigatorSeparator2
            // 
            SELF:bindingNavigatorSeparator2:Name := "bindingNavigatorSeparator2"
            SELF:bindingNavigatorSeparator2:Size := System.Drawing.Size{6, 27}
            // 
            // BrowseWindow3
            // 
            SELF:AutoScaleDimensions := System.Drawing.SizeF{8, 16}
            SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            SELF:ClientSize := System.Drawing.Size{535, 332}
            SELF:Controls:Add(SELF:bindingNavigator1)
            SELF:Controls:Add(SELF:panelMiddle)
            SELF:Controls:Add(SELF:statusStripBar)
            SELF:Margin := System.Windows.Forms.Padding{3, 2, 3, 2}
            SELF:Name := "BrowseWindow3"
            SELF:Text := "BrowseWindow"
            SELF:FormClosing += System.Windows.Forms.FormClosingEventHandler{ SELF, @BrowseWindow_FormClosing() }
            SELF:statusStripBar:ResumeLayout(false)
            SELF:statusStripBar:PerformLayout()
            SELF:panelMiddle:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(SELF:dbfBrowseView)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:bindingNavigator1)):EndInit()
            SELF:bindingNavigator1:ResumeLayout(false)
            SELF:bindingNavigator1:PerformLayout()
            ((System.ComponentModel.ISupportInitialize)(SELF:bindingSource1)):EndInit()
            SELF:ResumeLayout(false)
            SELF:PerformLayout()
                                                                                
        #endregion
    
    END CLASS 
END NAMESPACE
