//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.20.0.3
//     Timestamp      : 2024/8/17 7:45:40
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace FabDBFEd
    Public Partial Class DBFStructWindow ;
        Inherit System.Windows.Forms.Form
        Private colName As System.Windows.Forms.ColumnHeader
        Private colType As System.Windows.Forms.ColumnHeader
        Private colLength As System.Windows.Forms.ColumnHeader
        Private colDecimals As System.Windows.Forms.ColumnHeader
        Private addBtn As System.Windows.Forms.Button
        Private deleteBtn As System.Windows.Forms.Button
        Private saveBtn As System.Windows.Forms.Button
        Private fieldListView As System.Windows.Forms.ListView
        Private dbfRDD As System.Windows.Forms.ComboBox
        Private panel1 As System.Windows.Forms.Panel
        Private modelBtn As System.Windows.Forms.Button
        Private editBtn As System.Windows.Forms.Button
        Private closeBtn As System.Windows.Forms.Button
        Private components := Null As System.ComponentModel.IContainer
                                                                                                                                                                        
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Method Dispose(disposing As Logic) As Void Strict

            If (disposing .AND. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
            Return

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
                Private Method InitializeComponent() As Void Strict
            Local resources := System.ComponentModel.ComponentResourceManager{Typeof(DBFStructWindow)} As System.ComponentModel.ComponentResourceManager
            Self:fieldListView := System.Windows.Forms.ListView{}
            Self:colName := System.Windows.Forms.ColumnHeader{}
            Self:colType := System.Windows.Forms.ColumnHeader{}
            Self:colLength := System.Windows.Forms.ColumnHeader{}
            Self:colDecimals := System.Windows.Forms.ColumnHeader{}
            Self:addBtn := System.Windows.Forms.Button{}
            Self:deleteBtn := System.Windows.Forms.Button{}
            Self:saveBtn := System.Windows.Forms.Button{}
            Self:dbfRDD := System.Windows.Forms.ComboBox{}
            Self:panel1 := System.Windows.Forms.Panel{}
            Self:editBtn := System.Windows.Forms.Button{}
            Self:modelBtn := System.Windows.Forms.Button{}
            Self:closeBtn := System.Windows.Forms.Button{}
            Self:panel1:SuspendLayout()
            Self:SuspendLayout()
            // 
            // fieldListView
            // 
            resources:ApplyResources(Self:fieldListView, "fieldListView")
            Self:fieldListView:Columns:AddRange(<System.Windows.Forms.ColumnHeader>{ Self:colName, Self:colType, Self:colLength, Self:colDecimals })
            Self:fieldListView:FullRowSelect := true
            Self:fieldListView:GridLines := true
            Self:fieldListView:HeaderStyle := System.Windows.Forms.ColumnHeaderStyle.Nonclickable
            Self:fieldListView:HideSelection := false
            Self:fieldListView:MultiSelect := false
            Self:fieldListView:Name := "fieldListView"
            Self:fieldListView:UseCompatibleStateImageBehavior := false
            Self:fieldListView:View := System.Windows.Forms.View.Details
            Self:fieldListView:SelectedIndexChanged += System.EventHandler{ Self, @fieldListView_SelectedIndexChanged() }
            Self:fieldListView:MouseDoubleClick += System.Windows.Forms.MouseEventHandler{ Self, @fieldListView_MouseDoubleClick() }
            // 
            // colName
            // 
            resources:ApplyResources(Self:colName, "colName")
            // 
            // colType
            // 
            resources:ApplyResources(Self:colType, "colType")
            // 
            // colLength
            // 
            resources:ApplyResources(Self:colLength, "colLength")
            // 
            // colDecimals
            // 
            resources:ApplyResources(Self:colDecimals, "colDecimals")
            // 
            // addBtn
            // 
            resources:ApplyResources(Self:addBtn, "addBtn")
            Self:addBtn:Name := "addBtn"
            Self:addBtn:UseVisualStyleBackColor := true
            Self:addBtn:Click += System.EventHandler{ Self, @addBtn_Click() }
            // 
            // deleteBtn
            // 
            resources:ApplyResources(Self:deleteBtn, "deleteBtn")
            Self:deleteBtn:Name := "deleteBtn"
            Self:deleteBtn:UseVisualStyleBackColor := true
            Self:deleteBtn:Click += System.EventHandler{ Self, @deleteBtn_Click() }
            // 
            // saveBtn
            // 
            resources:ApplyResources(Self:saveBtn, "saveBtn")
            Self:saveBtn:Name := "saveBtn"
            Self:saveBtn:UseVisualStyleBackColor := true
            Self:saveBtn:Click += System.EventHandler{ Self, @saveBtn_Click() }
            // 
            // dbfRDD
            // 
            resources:ApplyResources(Self:dbfRDD, "dbfRDD")
            Self:dbfRDD:DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList
            Self:dbfRDD:FormattingEnabled := true
            Self:dbfRDD:Name := "dbfRDD"
            // 
            // panel1
            // 
            resources:ApplyResources(Self:panel1, "panel1")
            Self:panel1:Controls:Add(Self:dbfRDD)
            Self:panel1:Controls:Add(Self:editBtn)
            Self:panel1:Controls:Add(Self:deleteBtn)
            Self:panel1:Controls:Add(Self:addBtn)
            Self:panel1:Name := "panel1"
            // 
            // editBtn
            // 
            resources:ApplyResources(Self:editBtn, "editBtn")
            Self:editBtn:Name := "editBtn"
            Self:editBtn:TabStop := false
            Self:editBtn:UseVisualStyleBackColor := true
            Self:editBtn:Click += System.EventHandler{ Self, @editBtn_Click() }
            // 
            // modelBtn
            // 
            resources:ApplyResources(Self:modelBtn, "modelBtn")
            Self:modelBtn:Name := "modelBtn"
            Self:modelBtn:UseVisualStyleBackColor := true
            Self:modelBtn:Click += System.EventHandler{ Self, @modelBtn_Click() }
            // 
            // closeBtn
            // 
            resources:ApplyResources(Self:closeBtn, "closeBtn")
            Self:closeBtn:Name := "closeBtn"
            Self:closeBtn:UseVisualStyleBackColor := true
            Self:closeBtn:Click += System.EventHandler{ Self, @closeBtn_Click() }
            // 
            // DBFStructWindow
            // 
            Self:AcceptButton := Self:closeBtn
            resources:ApplyResources(Self, "$this")
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:Controls:Add(Self:closeBtn)
            Self:Controls:Add(Self:saveBtn)
            Self:Controls:Add(Self:modelBtn)
            Self:Controls:Add(Self:fieldListView)
            Self:Controls:Add(Self:panel1)
            Self:MaximizeBox := false
            Self:MinimizeBox := false
            Self:Name := "DBFStructWindow"
            Self:panel1:ResumeLayout(false)
            Self:ResumeLayout(false)
        End Method
                                            
        #endregion
    
    End Class 
End Namespace
